---
# tasks file for docker-install
# https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-20-04

- name: Install aptitude
  ansible.builtin.apt:
    name: aptitude
    state: present 
    update_cache: yes 

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - python3-apt
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-io
  ansible.builtin.apt:
    update_cache: true
    name: docker.io
    state: latest

- name: Install Docker Compose
  pip:
    name: docker-compose
    state: present

- name: Install mc (Midnight Commander)
  ansible.builtin.apt:
    name: mc
    state: present

- name: Install vim
  ansible.builtin.apt:
    name: vim
    state: present